### PR TITLE
fix Undefined index: _method

### PR DESCRIPTION
**Pull request by OmarMakled**
Undefined index: _method

create user uses default action POST and doesn't pass _method key

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
It should always be set.

**Comment by GrahamCampbell** [comment]
Can you send a PR to find the places where it's not set please.

**Comment by GrahamCampbell** [comment]
And set it.

**Comment by OmarMakled** [comment]
```
credentials/views/account/profile.blade.php
credentials/views/users/create.blade.php
credentials/views/users/edit.blade.php
```

**Pull request closed without merging**
